server:
  port: 8001
spring:
  main:
    allow-bean-definition-overriding: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  elasticsearch:
    rest:
      uris: http://192.168.200.100:9200

#暴露所有监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"